### ISSUE TITLE
[Documentation] Superclass used on the Concept context

### ISSUE THREAD

**Issue by viboes** [ldionne/hana#102]
The use of Superclass on the context of the type class definitions is weird. A type class (Concept) is not really a class. The relation of sub-class super-class is not defined. 

I suggest to use type class instead of concept, and define the relation of sub-type-class and super-type-class.

**Comment by ldionne** [comment]
I agree that using superclass is misleading. However, like I said in #97, I don't want to use "Type class" and related terms. I'll use the notion of "Refinement", which is the proper term for what I want to express and [has been used](https://www.sgi.com/tech/stl/stl_introduction.html) in C++ since the SGI STL.

**Comment by viboes** [comment]
I agree refinement is much better in some cases, but we have more than refinements as I've described in #104. We have just concrete models if you want, subject to some conditions.

**Comment by ldionne** [comment]
I understand. These would be much better described by "Requirements". Actually, the superclasses are sort of part of the minimal complete definition, in some sense.

**Comment by ldionne** [comment]
However, this issue of expressing

```haskell
Monoid a => Monoid (Maybe a)
```

is not really present in Hana, because it does not use parameterized tags. When a similar situation arises, I just describe it in words instead of having a notation for it, or a unifying notion of "requirements".
