### ISSUE TITLE
[Foldable] Why foldable mcd needs fold.left and fold.right?

### ISSUE THREAD

**Issue by viboes** [ldionne/hana#108]
Haskell `Foldable` type class has a `foldr` mcd. Why Hana needs `fold.left` and `fold.right`?

**Comment by ldionne** [comment]
If I remember correctly, it is because the default definition in terms of `foldr` was just way too inefficient. If you look at the definition from Haskell:

```haskell
foldl :: (b -> a -> b) -> b -> t a -> b
foldl f z t = appEndo (getDual (foldMap (Dual . Endo . flip f) t)) z
```

This uses `foldMap`, which is actually a `foldr`, to build a huge chain of function compositions, and then it throws the initial state (`z`) in there. With Hana, that would mean creating a huge chain of `compose`d function objects, and then calling that, which won't be efficient.

**Comment by viboes** [comment]
Couldn't fold_left be defined by default by some mcd?

Could the rationale be added to the documentation if not already there?

**Comment by ldionne** [comment]
I'll define `fold_right` in terms of `unpack`, which is itself defined in terms of `fold_left`.

I'll also add a note that the default implementation of `unpack` in terms of `fold_left` is pretty inefficient, so people should ideally define `unpack` if they want speed.
