### ISSUE TITLE
Document the versioning scheme

### ISSUE THREAD

**Issue by ldionne** [ldionne/hana#44]
We're currently in v0.1 and following the version scheme of [Semantic Versioning](http://semver.org), but this should be documented and detailed more precisely.

**Comment by ldionne** [comment]
Closed by 2f356a8. I suck at closing issues automatically from commits; I keep on doing typos.

**Comment by HaMster21** [comment]
I guess you're a human then :wink: 

:+1: for using semver

**Comment by ldionne** [comment]
I have no experience with this versioning system; we'll see how it goes. I am under the impression that I'll hit release 32.0.0 under no time, but I guess that'll motivate me to consider API-breaking changes more seriously :-).

**Comment by HaMster21** [comment]
I try to follow along since your talk at CppCon and at them moment I don't think that your are breaking your public API constantly. And you are in the middle of development anyways, so your API version would be some 0.x version. Breaking your public API becomes a serious issue if you publish a first version that you consider to be a **stable** 1.0.0 :wink: 

As long as you are adding functionality, just change the 0.x.y parts of the version, maybe with an additional _+ci-travis-[Travis build number]_ for a CI build if that ever goes public.
